
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/${app.auth-server.realm}/protocol/openid-connect/certs
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: eshop-gateway
            client-secret: 9289d4d6-c583-4edb-80b2-97d8d5a6db67
            authorization-grant-type: client_credentials
        #            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        #            scope: openid,profile,orders,basket
        provider:
          keycloak:
            token-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/${app.auth-server.realm}/protocol/openid-connect/token
#            authorization-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/auth
#            user-info-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#            jwk-set-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/certs

# Logging
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
      cloud.gateway.route.RouteDefinitionRouteLocator: INFO
      web.server.adapter.HttpWebHandlerAdapter: TRACE
