
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/${app.auth-server.realm}/protocol/openid-connect/certs

# Logging
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
      cloud.gateway.route.RouteDefinitionRouteLocator: INFO
      web.server.adapter.HttpWebHandlerAdapter: TRACE
