
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/${app.auth-server.realm}

# Logging
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
      cloud.gateway.route.RouteDefinitionRouteLocator: INFO
      web.server.adapter.HttpWebHandlerAdapter: TRACE
