app:
  security:
    oauth2.client:
      analytics: analytics-service

spring:
  security:
    oauth2:
      client:
        registration:
          analytics-service:
            provider: keycloak
            client-id: ${app.security.oauth2.client.analytics}
            client-secret: 9289d4d6-c583-4edb-80b2-97d8d5a6db67
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: ${app.auth-server.issuer-uri}

      resourceserver:
        jwt:
          issuer-uri: ${app.auth-server.issuer-uri}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    loadbalancer:
      ribbon:
        enabled: false
      retry:
        enabled: false

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
    instances:
      basket:
        baseConfig: default
      catalog:
        baseConfig: default
      order:
        baseConfig: default
        recordExceptions:
          - com.eshop.gateway.infrastructure.exception.ServiceCallFailedException

  retry:
    configs:
      default:
        maxRetryAttempts: 3
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
          - java.net.ConnectException
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable
#        ignoreExceptions:
#          - ...
    instances:
      basket:
        baseConfig: default
      catalog:
        baseConfig: default
        maxRetryAttempts: 4
        waitDuration: 200

  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      basket:
        baseConfig: default

  timelimiter:
    configs:
      default:
        cancelRunningFuture: false
        timeoutDuration: 2s
    instances:
      catalog:
        baseConfig: default
        cancelRunningFuture: true

# Logging
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
      cloud.gateway.route.RouteDefinitionRouteLocator: INFO
      web.server.adapter.HttpWebHandlerAdapter: TRACE
