
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/e-shop

# Logging
logging:
  level:
    org.springframework:
      cloud.gateway: TRACE
      cloud.gateway.route.RouteDefinitionRouteLocator: INFO
      web.server.adapter.HttpWebHandlerAdapter: TRACE
