# Custom config
app:
  postgres:
    host: localhost
    port: 5432
    database: dbcatalog

spring:
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.auth-server.jwk-set-uri}
          issuer-uri: ${app.auth-server.issuer-uri}
  # JPA
  jpa:
    hibernate:
      ddl-auto: validate

  # Postgres
  datasource:
    url: jdbc:postgresql://${app.postgres.host}:${app.postgres.port}/${app.postgres.database}
    username: dbuser
    password: dbpass
    driver-class-name: org.postgresql.Driver
