
# Eureka server
eureka:
  datacenter: Test Data Center
  environment: pevelopment
  client:
    register-with-eureka: false
    fetch-registry: false

# Logging
logging:level:
  com.netflix:
    eureka: DEBUG
    discovery: DEBUG
