
spring:
  # Security
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${app.auth-server.jwk-set-uri}
          issuer-uri: ${app.auth-server.issuer-uri}

logging:
  level:
    org:
      springframework:
        web: INFO
        security: DEBUG
    web: INFO
    root: INFO

