version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    restart: on-failure
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "product-feed:1:1"
    depends_on:
      - zookeeper
    links:
      - zookeeper

  postgres:
    build: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      PGTZ: Europe/Amsterdam

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      REDIS_PASSWORD: pass

  mariadb:
    image: mariadb
    ports:
      - 3306:3306
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
    volumes:
      - mysql_data:/var/lib/mysql

  authorization-service:
    image: quay.io/keycloak/keycloak:12.0.4
    ports:
      - 8090:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_IMPORT: /tmp/eshop-realm.json
    depends_on:
      - mariadb
    volumes:
      - ./keycloak/eshop-realm.json:/tmp/eshop-realm.json

volumes:
  mysql_data:
