version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - eshopnet
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    networks:
      - eshopnet
    ports:
      - 9092:9092
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    links:
      - zookeeper

  rabbitmq:
    image: 'rabbitmq:management'
    networks:
      - eshopnet
    ports:
      - 5672:5672
      - 15672:15672
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres:
    build: postgres
    networks:
      - eshopnet
    ports:
      - 5432:5432
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      PGTZ: Europe/Amsterdam
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    networks:
      - eshopnet
    ports:
      - 6379:6379
    restart: on-failure
    environment:
      REDIS_PASSWORD: pass

  authorization-service:
    image: jboss/keycloak:14.0.0
    networks:
      - eshopnet
    ports:
      - 8090:8080
    restart: on-failure
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_SCHEMA: public
      DB_USER: dbuser
      DB_PASSWORD: dbpass
      KEYCLOAK_IMPORT: /tmp/eshop-realm.json
    depends_on:
      - postgres
    volumes:
      - ./keycloak/eshop-realm.json:/tmp/eshop-realm.json

#  portainer:
#    image: portainer/portainer
#    networks:
#      - eshopnet
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./portainer-data:/data
#    ports:
#      - 9000:9000

networks:
  eshopnet:
    driver: bridge

volumes:
  mysql_data:
