version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    restart: on-failure
    environment:
      STORAGE_TYPE: mem
      RABBIT_ADDRESSES: rabbitmq
    depends_on:
      - rabbitmq
