version: '3.5'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:1:1,catalog:1:1,basket:1:1,payment:1:1"

#  kafka-manager:
#    container_name: kafka-manager
#    image: hlebalbau/kafka-manager:1.3.3.16
#    restart: on-failure
#    depends_on:
#      - kafka
#      - zookeeper
#    command: -Dconfig.file=/kafka-manager/conf/application.conf -Dapplication.home=/kafkamanager
#    environment:
#      ZK_HOSTS: zookeeper:2181
#    ports:
#      - 9000:9000

#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    restart: "no"
#    ports:
#      - 9000:9000
#    environment:
#      KAFKA_BROKERCONNECT: "kafka:29092"
#    depends_on:
#      - kafka
#
#  kafka:
#    image: obsidiandynamics/kafka
#    restart: "no"
#    ports:
#      - 2181:2181
#      - 9092:9092
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_PORT: 9092
#      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
#      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
#      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
#      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
#      KAFKA_CREATE_TOPICS: "order:1:1,catalog:1:1,basket:1:1,payment:1:1"

  postgres:
    build: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      PGTZ: Europe/Amsterdam

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=pass
