version: '3.5'

services:

  image-service:
    image: minimalcompact/thumbor
    ports:
      - 8887:80
    environment:
      # VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
      # but you usually need to point it to your domain, e.g. thumbor.example.com
      - VIRTUAL_HOST=localhost
      - UPLOAD_ENABLED=True
      - UPLOAD_MAX_SIZE=5000000 # 5Mb
      # returns a webp image if browser Accept headers match
      - AUTO_WEBP=True
      # nginx-proxy does caching automatically, so no need to store the result storage cache
      # (this greatly speeds up and saves on CPU)
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      - LOADER=thumbor.loaders.file_loader
      - FILE_LOADER_ROOT_PATH=/var/images
    restart: on-failure
    volumes:
      - ./images:/var/images
