server:
  port: 3000

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/certs
      client:
        registration:
          gateway:
            provider: keycloak
            client-id: eshop-gateway
            client-secret: f65e7259-cc66-47c4-9973-b5274858d19c
            authorization-grant-type: client_credentials
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: basket
        provider:
          keycloak:
#            authorization-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/auth
            token-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/token
#            user-info-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/userinfo
#            user-name-attribute: preferred_username
#            jwk-set-uri: http://localhost:8090/auth/realms/e-shop/protocol/openid-connect/certs
