spring:
  # JPA
  jpa:
    show-sql: false

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

---
spring:
  config:
    activate:
      on-profile: dev

  # JPA
  jpa:
    show-sql: false

  flyway:
    locations: classpath:db/migration, classpath:db/testdata
