# Custom config


app:
  postgres:
    host: localhost
    port: 5432
    database: dborders
    username: dbuser
    password: dbpass

  # JPA
  jpa:
    hibernate:
      ddl-auto: none

  # Postgres
  datasource:
    url: jdbc:postgresql://${app.postgres.host}:${app.postgres.port}/${app.postgres.database}
    username: ${app.postgres.username}
    password: ${app.postgres.password}
    driver-class-name: org.postgresql.Driver
